### ISSUE TITLE
Inconsistent winning displays. 

### ISSUE THREAD

**Issue by wjason00** [cam010/HiLo-Gambling-Game#1]
Sometimes the winning numbers have a lot of repeating 0's, causing the screen to change scaling. This likely stems from:

```python
text=f"WON: £{self.win_amount - self.bet_amount}")
```

e.g:

![Proof](https://user-images.githubusercontent.com/70390694/210173642-955345b4-b488-4ba9-8131-a3c37f263570.png)

**Comment by cam010** [comment]
Cheers for pointing it out
